### ISSUE TITLE
Sudden build errors from nowhere

### ISSUE THREAD

**Issue by pallaswept** [jersou/mouse-actions#21]
So, nothing changed here, nothing changed on my build, but now my build fails. I'm guessing some upstream node.js  dependency got updated and broke this:
```

[   94s] failed to load config from /home/abuild/rpmbuild/BUILD/mouse-actions/config-editor/vite.config.ts
[   94s] error during build:
[   94s] TypeError: Cannot redefine property: File
[   94s]     at Function.defineProperty (<anonymous>)
[   94s]     at Object.<anonymous> (/home/abuild/rpmbuild/BUILD/mouse-actions/config-editor/node_modules/@babel/core/lib/index.js:7:8)
[   94s]     at Module._compile (node:internal/modules/cjs/loader:1241:14)
[   94s]     at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
[   94s]     at Module.load (node:internal/modules/cjs/loader:1091:32)
[   94s]     at Module._load (node:internal/modules/cjs/loader:938:12)
[   94s]     at Module.require (node:internal/modules/cjs/loader:1115:19)
[   94s]     at require (node:internal/modules/helpers:130:18)
[   94s]     at Object.<anonymous> (/home/abuild/rpmbuild/BUILD/mouse-actions/config-editor/node_modules/@babel/core/lib/config/helpers/config-api.js:16:9)
[   94s]     at Module._compile (node:internal/modules/cjs/loader:1241:14)
[   94s]        Error beforeBuildCommand `npm run build` failed with exit code 1
[   94s] error: Bad exit status from /var/tmp/rpm-tmp.Cj577C (%build)

```
I guess this just needs either babel or cjs to be resricted to an older version or something? I'm a node.js idiot so I've not a lot of clue here. All I know is it's been fine for months, I changed nothing and you changed nothing, and it broke.

Any ideas?

**Comment by pallaswept** [comment]
Whatever broke upstream fixed itself upstream and the build just magically worked again. Yay :)
